- name: bird-monitor user is present
  ansible.builtin.user:
    name: bird-monitor
    group: bird
    system: true
    state: present

- name: birdcl utility is present
  ansible.builtin.file:
    path: /usr/sbin/birdcl
    state: file

- name: bird-monitor script file is present
  ansible.builtin.copy:
    src: "{{ bird2_monitor_script }}"
    dest: /usr/local/bin/bird_monitor_script
    mode: 0755
    owner: root
    group: root
  notify: restart bird-monitor.service

- name: bird-monitor.service is defined
  ansible.builtin.copy:
    src: bird-monitor.service
    dest: /etc/systemd/system/
    mode: 0644
    owner: root
    group: root
  notify: restart bird-monitor.service
