---
- name: Reload bird
  ansible.builtin.service:
    name: bird
    enabled: true
    state: reloaded
  ignore_errors: "{{ ansible_check_mode }}"

- name: restart bird-monitor.service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: bird-monitor
    state: restarted
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
